---
- name: Install python3, docker, docker-compose
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      get_url:
        # url uses 'lookup' plugin which is an Ansible-specific extension to Jinja
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    # uses systemd module to work with services
    - name: start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker python modules
      pip:
        name:
          - docker
          - docker-compose